// auto generated by c2z
const std = @import("std");
//const cpp = @import("cpp");

pub extern fn addTextureEx(pRenderer: [*c]Renderer, pTextureDesc: [*c]const TextureDesc, texture: [*c][*c]Texture, bBindless: bool) void;
pub extern fn removeTextureEx(pRenderer: [*c]Renderer, ppTexture: [*c]Texture) void;
