// auto generated by c2z
const std = @import("std");
const zgraphics = @import("IGraphics.zig");
//const cpp = @import("cpp");

pub extern fn initGPUConfigurationEx(pExtendedSettings: [*c]zgraphics.ExtendedSettings) void;
pub extern fn exitGPUConfigurationEx() void;
pub extern fn addTextureEx(pRenderer: [*c]zgraphics.Renderer, pTextureDesc: [*c]const zgraphics.TextureDesc, texture: [*c][*c]zgraphics.Texture, bBindless: bool) void;
pub extern fn removeTextureEx(pRenderer: [*c]zgraphics.Renderer, ppTexture: [*c]zgraphics.Texture) void;
